version: "3"
services:
    datastore:
        image: ealgis/postgis:latest
        volumes:
            - ./:/app
        environment:
            - POSTGRES_DB=ealgis
        ports:
            - "5432:5432"

    dataloader:
        image: ealgis/ingest-base:latest
        volumes:
            - ./:/app
            # - ./ealgis-common:/ealgis-common
        environment:
            - DB_HOST=datastore
            - DB_PORT=5432
            - DB_NAME=postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
        depends_on:
            - datastore
